# Generated by Django 5.2.4 on 2025-07-23 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0002_admin_hr_student_tpo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('file', models.FileField(upload_to='certifications/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DriveJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('eligibility', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='tpo',
            old_name='office',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='admin',
            name='can_add_courses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='can_add_training_drives',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='can_add_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='admin@placeholder.com', max_length=254),
        ),
        migrations.AddField(
            model_name='admin',
            name='full_name',
            field=models.CharField(default='Admin User', max_length=100),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='hr',
            name='company_name',
            field=models.CharField(default='Placeholder Company', max_length=255),
        ),
        migrations.AddField(
            model_name='hr',
            name='company_website',
            field=models.URLField(blank=True, default='https://example.com'),
        ),
        migrations.AddField(
            model_name='hr',
            name='designation',
            field=models.CharField(default='HR', max_length=100),
        ),
        migrations.AddField(
            model_name='hr',
            name='email',
            field=models.EmailField(default='hr@placeholder.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hr',
            name='full_name',
            field=models.CharField(default='HR User', max_length=100),
        ),
        migrations.AddField(
            model_name='hr',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='hr',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='Your Institution Name', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='course_enrolled',
            field=models.CharField(default='Course', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='Department', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='student@placeholder.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Student User', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='placement_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tpo',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='tpo_assigned', to='Donotechapp.student'),
        ),
        migrations.AddField(
            model_name='tpo',
            name='designation',
            field=models.CharField(default='TPO', max_length=100),
        ),
        migrations.AddField(
            model_name='tpo',
            name='email',
            field=models.EmailField(default='tpo@placeholder.com', max_length=254),
        ),
        migrations.AddField(
            model_name='tpo',
            name='full_name',
            field=models.CharField(default='TPO User', max_length=100),
        ),
        migrations.AddField(
            model_name='tpo',
            name='joined_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='tpo',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='tpo',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tpo_profiles/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='TEMPID', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='Donotechapp.certification'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses_registered',
            field=models.ManyToManyField(blank=True, to='Donotechapp.course'),
        ),
        migrations.AddField(
            model_name='hr',
            name='job_postings',
            field=models.ManyToManyField(blank=True, related_name='hr_jobs', to='Donotechapp.drivejob'),
        ),
        migrations.AddField(
            model_name='student',
            name='placement_applications',
            field=models.ManyToManyField(blank=True, related_name='applied_students', to='Donotechapp.drivejob'),
        ),
        migrations.AddField(
            model_name='tpo',
            name='drives_managed',
            field=models.ManyToManyField(blank=True, related_name='tpo_drives', to='Donotechapp.drivejob'),
        ),
    ]
