# Generated by Django 5.2.4 on 2025-07-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0003_certification_course_drivejob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college_completed',
            field=models.BooleanField(default=False),
        ),
    ]
