# Generated by Django 5.2.4 on 2025-07-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0005_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college_completed',
        ),
    ]
