# Generated by Django 5.2.4 on 2025-07-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0006_remove_student_college_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_semester',
            field=models.CharField(choices=[('0', 'College Completed'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=2),
        ),
    ]
