# Generated by Django 5.2.4 on 2025-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0007_alter_student_year_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_semester',
            field=models.CharField(choices=[('College Completed', 'College Completed'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='College Completed', max_length=17),
        ),
    ]
