# Generated by Django 5.2.4 on 2025-07-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0008_alter_student_year_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpo',
            name='office',
            field=models.CharField(default='TPO Office', max_length=100),
        ),
    ]
