# Generated by Django 5.2.4 on 2025-07-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0009_tpo_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
