# Generated by Django 5.2.4 on 2025-07-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0010_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('HR', 'HR'), ('STUDENT', 'STUDENT'), ('TPO', 'TPO')], default='STUDENT', max_length=10),
        ),
    ]
