# Generated by Django 5.2.4 on 2025-07-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0011_certification_description_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivejob',
            name='job_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
