# Generated by Django 5.2.4 on 2025-07-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0014_programcategory_program'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ProgramCategory',
        ),
    ]
