# Generated by Django 5.2.4 on 2025-07-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0015_delete_program_delete_programcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the course', max_length=100, verbose_name='Course Name')),
                ('description', models.TextField(help_text='Provide a detailed description of the course', verbose_name='Course Description')),
                ('image', models.ImageField(help_text='Upload an image representing the course', upload_to='courses/', verbose_name='Course Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this course should be displayed', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
