# Generated by Django 5.2.4 on 2025-07-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0016_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for this course', null=True, upload_to='course_images/')),
                ('apply_link', models.URLField(default='/contact/', help_text='Link to the application/contact page')),
            ],
            options={
                'verbose_name': 'Course Program',
                'verbose_name_plural': 'Course Programs',
            },
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
