# Generated by Django 5.2.4 on 2025-07-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0018_delete_course_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tieup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tieup',
            name='name',
        ),
    ]
