# Generated by Django 5.2.4 on 2025-07-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0019_remove_tieup_description_remove_tieup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='company',
        ),
    ]
