# Generated by Django 5.1.1 on 2025-07-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0020_remove_mentor_bio_remove_mentor_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='MediaCoverage',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
