# Generated by Django 5.1.1 on 2025-07-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0022_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='placement_applications',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='job_postings',
        ),
        migrations.RemoveField(
            model_name='tpo',
            name='drives_managed',
        ),
        migrations.RemoveField(
            model_name='hr',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tpo',
            name='assigned_students',
        ),
        migrations.RemoveField(
            model_name='tpo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='placement_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='year_semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='College Completed', max_length=17),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'STUDENT')], default='STUDENT', max_length=10),
        ),
        migrations.DeleteModel(
            name='DriveJob',
        ),
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.DeleteModel(
            name='TPO',
        ),
    ]
