# Generated by Django 5.1.1 on 2025-07-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0023_remove_student_placement_applications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='tools',
        ),
    ]
