# Generated by Django 5.1.1 on 2025-07-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0025_courseitem_semester_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_enrolled',
        ),
        migrations.AlterField(
            model_name='student',
            name='year_semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='0', max_length=17),
        ),
    ]
