# Generated by Django 5.1.1 on 2025-07-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0026_remove_student_course_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='student@gmail.com', max_length=254),
        ),
    ]
