# Generated by Django 5.1.1 on 2025-07-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0029_mentor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mentor',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'STUDENT')], default='STUDENT', max_length=10),
        ),
    ]
