# Generated by Django 5.1.1 on 2025-07-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0031_alter_userprofile_role_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='company',
        ),
    ]
