# Generated by Django 5.1.1 on 2025-07-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0034_alter_staff_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentExperience',
        ),
    ]
