# Generated by Django 5.1.1 on 2025-07-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0035_delete_studentexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
    ]
