# Generated by Django 5.1.1 on 2025-07-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0037_tieup_name_mentorsession_mentortask_courseprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentortask',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='MentorSession',
        ),
        migrations.DeleteModel(
            name='MentorTask',
        ),
    ]
