# Generated by Django 5.1.1 on 2025-08-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0039_resume_project_language_experience_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='language',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='project',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='student',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='resume',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
