# Generated by Django 5.1.1 on 2025-08-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0040_remove_education_resume_remove_experience_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(default='Your College Name', max_length=255),
        ),
    ]
