# Generated by Django 5.1.1 on 2025-08-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donotechapp', '0041_alter_student_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staff',
        ),
    ]
